"""create tables

Revision ID: 80bbef5b0ad4
Revises: b5f9e754d7a2
Create Date: 2025-11-12 20:13:05.032289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80bbef5b0ad4'
down_revision = 'b5f9e754d7a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_column('students', 'email')
    op.drop_column('students', 'phone_number')
    # ### end Alembic commands ###
