"""create tables

Revision ID: a9b66a4deb96
Revises: 
Create Date: 2025-11-14 06:16:51.223074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b66a4deb96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_candidates', sa.Integer(), nullable=False),
    sa.Column('voting_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_index(op.f('ix_portfolios_name'), 'portfolios', ['name'], unique=True)
    op.create_table('registration_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('link_token', sa.String(length=128), nullable=False),
    sa.Column('max_devices', sa.Integer(), nullable=False),
    sa.Column('current_device_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_links_id'), 'registration_links', ['id'], unique=False)
    op.create_index(op.f('ix_registration_links_link_token'), 'registration_links', ['link_token'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('program', sa.String(length=100), nullable=True),
    sa.Column('year_level', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('voting_pin_hash', sa.String(length=128), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('has_voted', sa.Boolean(), nullable=False),
    sa.Column('voted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_students_device_fingerprint'), 'students', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=False)
    op.create_index(op.f('ix_students_has_voted'), 'students', ['has_voted'], unique=False)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)
    op.create_table('candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('picture_url', sa.String(length=500), nullable=True),
    sa.Column('picture_filename', sa.String(length=255), nullable=True),
    sa.Column('manifesto', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_index(op.f('ix_candidates_name'), 'candidates', ['name'], unique=False)
    op.create_index(op.f('ix_candidates_portfolio_id'), 'candidates', ['portfolio_id'], unique=False)
    op.create_table('device_registrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('location_data', sa.JSON(), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('registration_link_id', sa.Uuid(), nullable=True),
    sa.Column('electorate_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('biometric_data_hash', sa.String(length=128), nullable=True),
    sa.Column('device_password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.String(length=255), nullable=True),
    sa.Column('ban_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_attempt_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['electorate_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['registration_link_id'], ['registration_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_registrations_device_fingerprint'), 'device_registrations', ['device_fingerprint'], unique=True)
    op.create_index(op.f('ix_device_registrations_electorate_id'), 'device_registrations', ['electorate_id'], unique=False)
    op.create_index(op.f('ix_device_registrations_id'), 'device_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_device_registrations_ip_address'), 'device_registrations', ['ip_address'], unique=False)
    op.create_index(op.f('ix_device_registrations_registration_link_id'), 'device_registrations', ['registration_link_id'], unique=False)
    op.create_table('voting_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('electorate_id', sa.Uuid(), nullable=False),
    sa.Column('session_token', sa.String(length=128), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('user_agent_hash', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('login_method', sa.String(length=50), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('last_activity_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('terminated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('termination_reason', sa.String(length=255), nullable=True),
    sa.Column('suspicious_activity', sa.Boolean(), nullable=False),
    sa.Column('activity_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['electorate_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voting_sessions_device_fingerprint'), 'voting_sessions', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_voting_sessions_electorate_id'), 'voting_sessions', ['electorate_id'], unique=False)
    op.create_index(op.f('ix_voting_sessions_id'), 'voting_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_voting_sessions_ip_address'), 'voting_sessions', ['ip_address'], unique=False)
    op.create_index(op.f('ix_voting_sessions_session_token'), 'voting_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_voting_sessions_user_agent_hash'), 'voting_sessions', ['user_agent_hash'], unique=False)
    op.create_table('voting_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('electorate_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('device_info', sa.JSON(), nullable=False),
    sa.Column('location_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('biometric_data_hash', sa.String(length=128), nullable=True),
    sa.Column('device_password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['electorate_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voting_tokens_device_fingerprint'), 'voting_tokens', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_voting_tokens_electorate_id'), 'voting_tokens', ['electorate_id'], unique=False)
    op.create_index(op.f('ix_voting_tokens_id'), 'voting_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_voting_tokens_ip_address'), 'voting_tokens', ['ip_address'], unique=False)
    op.create_index(op.f('ix_voting_tokens_token_hash'), 'voting_tokens', ['token_hash'], unique=True)
    op.create_table('votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('electorate_id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('voting_session_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('voted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['electorate_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['voting_session_id'], ['voting_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_candidate_id'), 'votes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_votes_device_fingerprint'), 'votes', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_votes_electorate_id'), 'votes', ['electorate_id'], unique=False)
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=False)
    op.create_index(op.f('ix_votes_ip_address'), 'votes', ['ip_address'], unique=False)
    op.create_index(op.f('ix_votes_portfolio_id'), 'votes', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_votes_voting_session_id'), 'votes', ['voting_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_voting_session_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_portfolio_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_ip_address'), table_name='votes')
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_electorate_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_device_fingerprint'), table_name='votes')
    op.drop_index(op.f('ix_votes_candidate_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_voting_tokens_token_hash'), table_name='voting_tokens')
    op.drop_index(op.f('ix_voting_tokens_ip_address'), table_name='voting_tokens')
    op.drop_index(op.f('ix_voting_tokens_id'), table_name='voting_tokens')
    op.drop_index(op.f('ix_voting_tokens_electorate_id'), table_name='voting_tokens')
    op.drop_index(op.f('ix_voting_tokens_device_fingerprint'), table_name='voting_tokens')
    op.drop_table('voting_tokens')
    op.drop_index(op.f('ix_voting_sessions_user_agent_hash'), table_name='voting_sessions')
    op.drop_index(op.f('ix_voting_sessions_session_token'), table_name='voting_sessions')
    op.drop_index(op.f('ix_voting_sessions_ip_address'), table_name='voting_sessions')
    op.drop_index(op.f('ix_voting_sessions_id'), table_name='voting_sessions')
    op.drop_index(op.f('ix_voting_sessions_electorate_id'), table_name='voting_sessions')
    op.drop_index(op.f('ix_voting_sessions_device_fingerprint'), table_name='voting_sessions')
    op.drop_table('voting_sessions')
    op.drop_index(op.f('ix_device_registrations_registration_link_id'), table_name='device_registrations')
    op.drop_index(op.f('ix_device_registrations_ip_address'), table_name='device_registrations')
    op.drop_index(op.f('ix_device_registrations_id'), table_name='device_registrations')
    op.drop_index(op.f('ix_device_registrations_electorate_id'), table_name='device_registrations')
    op.drop_index(op.f('ix_device_registrations_device_fingerprint'), table_name='device_registrations')
    op.drop_table('device_registrations')
    op.drop_index(op.f('ix_candidates_portfolio_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_name'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_has_voted'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index(op.f('ix_students_device_fingerprint'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_registration_links_link_token'), table_name='registration_links')
    op.drop_index(op.f('ix_registration_links_id'), table_name='registration_links')
    op.drop_table('registration_links')
    op.drop_index(op.f('ix_portfolios_name'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
